local helpers = require("helpers")
local scratch = require("scratch_comments")
local state = require("scratch_comments.state")
local expect = MiniTest.expect

local function only()
  return state.anchored()[1]
end

before_each(function()
  helpers.reset()
end)

describe("a line comment", function()
  before_each(function()
    helpers.buffer("anchoring.md", { "one", "two", "the quick brown fox", "four", "five" })
    vim.cmd("3Comment")
    helpers.write("on the fox")
  end)

  it("follows its text when lines are inserted above", function()
    vim.api.nvim_buf_set_lines(0, 0, 0, false, { "new a", "new b", "new c" })
    expect.equality(only().start_line, 6)
    expect.equality(only().end_line, 6)
    expect.equality(scratch.render():match("%- (line %d+)"), "line 6")
  end)

  it("follows its text when lines above are deleted", function()
    vim.api.nvim_buf_set_lines(0, 0, 2, false, {})
    expect.equality(only().start_line, 1)
  end)

  it("reads its snippet live", function()
    vim.api.nvim_buf_set_text(0, 2, 4, 2, 9, { "slow" })
    expect.equality(only().snippet, "the slow brown fox")
  end)

  it("stays anchored when part of the line is edited", function()
    vim.api.nvim_win_set_cursor(0, { 3, 4 })
    vim.cmd("normal! ciwslow")
    expect.equality(#state.anchored(), 1)
  end)

  it("stays anchored when the whole line is rewritten", function()
    vim.api.nvim_win_set_cursor(0, { 3, 0 })
    vim.cmd("normal! ccthe slow fox")
    expect.equality(#state.orphans(), 0)
  end)
end)

describe("a range comment", function()
  before_each(function()
    helpers.buffer("anchoring.md", { "a", "b", "c", "d", "e" })
    vim.cmd("2,4Comment")
    helpers.write("on b through d")
  end)

  it("covers its lines", function()
    expect.equality(only().start_line, 2)
    expect.equality(only().end_line, 4)
  end)

  it("grows when lines are inserted inside it", function()
    vim.api.nvim_buf_set_lines(0, 2, 2, false, { "inside" })
    expect.equality(only().start_line, 2)
    expect.equality(only().end_line, 5)
  end)

  it("shrinks when its last line is deleted, without taking in the next line", function()
    vim.api.nvim_buf_set_lines(0, 3, 4, false, {})
    expect.equality(only().end_line, 3)
    expect.equality(only().snippet, "b\nc")
  end)

  it("stays anchored when one of its lines is rewritten", function()
    vim.api.nvim_win_set_cursor(0, { 3, 0 })
    vim.cmd("normal! ccrewritten")
    expect.equality(#state.orphans(), 0)
  end)

  it("shrinks when a middle line is deleted", function()
    vim.cmd("3d")
    expect.equality(#state.orphans(), 0)
    expect.equality(only().end_line, 3)
  end)
end)

describe("an orphan", function()
  before_each(function()
    helpers.buffer("anchoring.md", { "one", "two", "the quick fox", "four", "five" })
    vim.cmd("3Comment")
    helpers.write("on the fox")
    helpers.undo_break()
    vim.cmd("3d")
    helpers.text_changed()
  end)

  it("is what a comment becomes when its lines are deleted", function()
    expect.equality(#state.anchored(), 0)
    expect.equality(#state.orphans(), 1)
  end)

  it("has no sign", function()
    local namespace = vim.api.nvim_get_namespaces().scratch_comments_signs
    expect.equality(#vim.api.nvim_buf_get_extmarks(0, namespace, 0, -1, {}), 0)
  end)

  it("is exported in its own section, with its text", function()
    local markdown = scratch.render()
    expect.no_equality(markdown:find("## Orphaned", 1, true), nil)
    expect.no_equality(markdown:find("on the fox", 1, true), nil)
  end)

  it("is in the list, marked", function()
    vim.cmd("CommentList")
    local entries = vim.fn.getqflist()
    expect.equality(#entries, 1)
    expect.no_equality(entries[1].text:find("[orphaned]", 1, true), nil)
    vim.cmd("cclose")
  end)

  it("is anchored again by undo", function()
    helpers.undo_break()
    vim.cmd("silent undo")
    expect.equality(#state.orphans(), 0)
    expect.equality(only().start_line, 3)
  end)

  it("is offered by :CommentDelete on a line without comments", function()
    helpers.pick(1)
    vim.api.nvim_win_set_cursor(0, { 1, 0 })
    vim.cmd("CommentDelete")
    expect.equality(#helpers.offered, 1)
    expect.equality(#state.orphans(), 0)
  end)
end)

describe("a file's comments", function()
  before_each(function()
    vim.cmd.edit("tests/fixtures/lifecycle.txt")
    vim.cmd("Comment")
    helpers.write("on the first line")
  end)

  it("survive :e!", function()
    vim.cmd("edit!")
    expect.equality(#state.anchored(), 1)
  end)

  it("go with :bd", function()
    vim.cmd("bdelete")
    expect.equality(#state.all(), 0)
  end)
end)
