local helpers = require("helpers")
local views = require("scratch_comments.model.views")
local store = require("scratch_comments.model.store")
local expect = MiniTest.expect

before_each(function()
  helpers.reset()
  helpers.buffer("notes.md", { "one", "two", "three", "four" })
  vim.cmd("1Comment")
  helpers.write("on one")
  vim.cmd("1,3Comment")
  helpers.write("on one to three")
  vim.cmd.CommentList()
end)

describe(":CommentDelete", function()
  it("does not delete a merely selected quickfix entry", function()
    vim.api.nvim_win_set_cursor(0, { 2, 0 })
    vim.cmd.CommentDelete()
    expect.equality(#store.all(), 2)
    expect.equality(helpers.notified()[#helpers.notified()], "No comment card open")
  end)

  it("deletes the focused card by its ID", function()
    vim.cmd("normal \r")
    vim.cmd.CommentDelete()
    vim.wait(0)
    expect.equality(#store.all(), 1)
    expect.equality(views.anchored()[1].comment, "on one to three")
  end)

  it("keeps quickfix focus when invoked there while an editor is open", function()
    local qf_win = vim.api.nvim_get_current_win()
    vim.cmd("normal \r")
    vim.api.nvim_set_current_win(qf_win)
    vim.cmd.CommentDelete()
    vim.wait(0)
    expect.equality(vim.api.nvim_get_current_win(), qf_win)
    expect.equality(#store.all(), 1)
  end)

  it("does nothing after a card has closed", function()
    vim.cmd("normal \r")
    vim.cmd.quit()
    vim.cmd.CommentDelete()
    expect.equality(#store.all(), 2)
    expect.equality(helpers.notified()[#helpers.notified()], "No comment card open")
  end)

  it("protects unsaved changes", function()
    vim.cmd("normal \r")
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "unsaved" })
    vim.cmd.CommentDelete()
    expect.equality(#store.all(), 2)
    expect.equality(helpers.notified()[#helpers.notified()], "Save or discard the comment first")
  end)
end)

describe("saving an empty comment", function()
  it("deletes the edited comment and closes its card", function()
    vim.cmd("normal \r")
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "" })
    vim.cmd.write()
    vim.wait(0)
    expect.equality(#store.all(), 1)
    expect.equality(views.anchored()[1].comment, "on one to three")
    expect.equality(#vim.fn.getqflist(), 1)
  end)

  it("does not delete it when empty changes are discarded", function()
    vim.cmd("normal \r")
    vim.api.nvim_buf_set_lines(0, 0, -1, false, { "" })
    vim.cmd("q!")
    expect.equality(#store.all(), 2)
  end)
end)

describe(":CommentClear", function()
  it("removes every comment and its marks", function()
    local source = assert(views.anchored()[1].bufnr)
    vim.cmd("CommentClear")
    local namespace = vim.api.nvim_get_namespaces().scratch_comments
    expect.equality(#store.all(), 0)
    expect.equality(#vim.api.nvim_buf_get_extmarks(source, namespace, 0, -1, {}), 0)
  end)
end)
