local helpers = require("helpers")
local state = require("scratch_comments.state")
local expect = MiniTest.expect

before_each(function()
  helpers.reset()
  helpers.buffer("notes.md", { "one", "two", "three", "four" })
  vim.cmd("1Comment")
  helpers.write("on one")
  vim.cmd("1,3Comment")
  helpers.write("on one to three")
  vim.api.nvim_win_set_cursor(0, { 1, 0 })
end)

describe(":CommentShow", function()
  it("asks which comment when several cover the line", function()
    helpers.pick(2)
    vim.cmd("CommentShow")
    expect.equality(#helpers.offered, 2)
    expect.equality(helpers.text(), "on one to three")
  end)

  it("saves edits to the comment it shows", function()
    helpers.pick(2)
    vim.cmd("CommentShow")
    helpers.write("picked the range")
    expect.equality(#state.all(), 2)
    expect.equality(state.anchored()[2].comment, "picked the range")
  end)

  it("opens nothing when the picker is cancelled", function()
    helpers.pick(0)
    vim.cmd("CommentShow")
    expect.equality(#helpers.floats(), 0)
  end)

  it("closes with :q", function()
    helpers.pick(2)
    vim.cmd("CommentShow")
    vim.cmd("quit")
    expect.equality(#helpers.floats(), 0)
  end)
end)

describe(":CommentDelete", function()
  it("deletes the picked comment", function()
    helpers.pick(1)
    vim.cmd("CommentDelete")
    expect.equality(#state.all(), 1)
    expect.equality(state.anchored()[1].comment, "on one to three")
  end)

  it("deletes nothing when the picker is cancelled", function()
    helpers.pick(0)
    vim.cmd("CommentDelete")
    expect.equality(#state.all(), 2)
  end)

  it("says so on a line with no comment and no orphans", function()
    vim.api.nvim_win_set_cursor(0, { 4, 0 })
    vim.cmd("CommentDelete")
    expect.equality(#state.all(), 2)
    expect.equality(helpers.notified()[#helpers.notified()], "No comment at cursor")
  end)
end)

describe(":CommentClear", function()
  it("removes every comment and its marks", function()
    vim.cmd("CommentClear")
    local namespace = vim.api.nvim_get_namespaces().scratch_comments
    expect.equality(#state.all(), 0)
    expect.equality(#vim.api.nvim_buf_get_extmarks(0, namespace, 0, -1, {}), 0)
  end)
end)
